language: php
php:
  - 5.3
  - 5.4
before_script:
  - sudo apt-get install llvm-3.0 llvm-3.0-dev llvm-3.0-runtime
  - phpize
  - ./configure --with-llvm-config=/usr/bin/llvm-config-3.0 --enable-defult-callback
script: echo 'n'|make test