char *triggerCallback_ir = "%struct.__va_list_tag = type { i32, i32, i8*, i8* }\n"
"\n"
"@callbackObj = global i8* null, align 8\n"
"@LLVMBind_triggerCallback = global void (i8*, i8*, i32, i8*, %struct.__va_list_tag*)* null, align 8\n"
"\n"
"define void @LLVMBind_setTriggerCallbackEntryPoint(i8* %object, void (i8*, i8*, i32, i8*, %struct.__va_list_tag*)* %call) nounwind uwtable {\n"
"entry:\n"
"  %0 = load i8** @callbackObj, align 8\n"
"  %tobool = icmp eq i8* %0, null\n"
"  br i1 %tobool, label %if.end, label %return\n"
"\n"
"if.end:                                           ; preds = %entry\n"
"  store i8* %object, i8** @callbackObj, align 8\n"
"  store void (i8*, i8*, i32, i8*, %struct.__va_list_tag*)* %call, void (i8*, i8*, i32, i8*, %struct.__va_list_tag*)** @LLVMBind_triggerCallback, align 8\n"
"  br label %return\n"
"\n"
"return:                                           ; preds = %entry, %if.end\n"
"  ret void\n"
"}\n"
"\n"
"define void @triggerCallback(i32 %callbackIndex, i8* %retval, i8* %argsDefine, ...) nounwind uwtable {\n"
"entry:\n"
"  %ap = alloca [1 x %struct.__va_list_tag], align 16\n"
"  %arraydecay = getelementptr inbounds [1 x %struct.__va_list_tag]* %ap, i64 0, i64 0\n"
"  %arraydecay1 = bitcast [1 x %struct.__va_list_tag]* %ap to i8*\n"
"  call void @llvm.va_start(i8* %arraydecay1)\n"
"  %0 = load void (i8*, i8*, i32, i8*, %struct.__va_list_tag*)** @LLVMBind_triggerCallback, align 8\n"
"  %1 = load i8** @callbackObj, align 8\n"
"  call void %0(i8* %1, i8* %retval, i32 %callbackIndex, i8* %argsDefine, %struct.__va_list_tag* %arraydecay) nounwind\n"
"  call void @llvm.va_end(i8* %arraydecay1)\n"
"  ret void\n"
"}\n"
"\n"
"declare void @llvm.va_start(i8*) nounwind\n"
"\n"
"declare void @llvm.va_end(i8*) nounwind\n";
