char *triggerCallback_ir = "; ModuleID = \'bitcode/triggerCallback.c\'\n"
"target datalayout = \"e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128\"\n"
"target triple = \"x86_64-unknown-linux-gnu\"\n"
"\n"
"%struct.__va_list_tag = type { i32, i32, i8*, i8* }\n"
"\n"
"@callbackObj = global i8* null, align 8\n"
"@LLVMBind_triggerCallback = global void (i8*, i32, i8*, %struct.__va_list_tag*)* null, align 8\n"
"\n"
"define void @LLVMBind_setTriggerCallbackEntryPoint(i8* %object, void (i8*, i32, i8*, %struct.__va_list_tag*)* %call) nounwind uwtable {\n"
"entry:\n"
"  %0 = load i8** @callbackObj, align 8, !tbaa !0\n"
"  %tobool = icmp eq i8* %0, null\n"
"  br i1 %tobool, label %if.end, label %return\n"
"\n"
"if.end:                                           ; preds = %entry\n"
"  store i8* %object, i8** @callbackObj, align 8, !tbaa !0\n"
"  store void (i8*, i32, i8*, %struct.__va_list_tag*)* %call, void (i8*, i32, i8*, %struct.__va_list_tag*)** @LLVMBind_triggerCallback, align 8, !tbaa !0\n"
"  br label %return\n"
"\n"
"return:                                           ; preds = %entry, %if.end\n"
"  ret void\n"
"}\n"
"\n"
"define void @triggerCallback(i32 %callbackIndex, i8* %argsDefine, ...) nounwind uwtable {\n"
"entry:\n"
"  %ap = alloca [1 x %struct.__va_list_tag], align 16\n"
"  %arraydecay = getelementptr inbounds [1 x %struct.__va_list_tag]* %ap, i64 0, i64 0\n"
"  %arraydecay1 = bitcast [1 x %struct.__va_list_tag]* %ap to i8*\n"
"  call void @llvm.va_start(i8* %arraydecay1)\n"
"  %0 = load void (i8*, i32, i8*, %struct.__va_list_tag*)** @LLVMBind_triggerCallback, align 8, !tbaa !0\n"
"  %1 = load i8** @callbackObj, align 8, !tbaa !0\n"
"  call void %0(i8* %1, i32 %callbackIndex, i8* %argsDefine, %struct.__va_list_tag* %arraydecay) nounwind\n"
"  call void @llvm.va_end(i8* %arraydecay1)\n"
"  ret void\n"
"}\n"
"\n"
"declare void @llvm.va_start(i8*) nounwind\n"
"\n"
"declare void @llvm.va_end(i8*) nounwind\n"
"\n"
"!0 = metadata !{metadata !\"any pointer\", metadata !1}\n"
"!1 = metadata !{metadata !\"omnipotent char\", metadata !2}\n"
"!2 = metadata !{metadata !\"Simple C/C++ TBAA\"}\n";
